package in.thetechguru.quote.quotealot.activity;

import android.arch.lifecycle.LifecycleFragment;
import android.arch.lifecycle.ViewModelProviders;
import android.content.Context;
import android.os.AsyncTask;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.widget.SwipeRefreshLayout;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import java.util.List;

import in.thetechguru.quote.quotealot.R;
import in.thetechguru.quote.quotealot.adapter.AdapterQuotesSaved;
import in.thetechguru.quote.quotealot.viewmodel.POJO.SavedQuote;
import in.thetechguru.quote.quotealot.viewmodel.QuoteViewModel;

/**
 * Created by AB on 7/1/2017.
 */

public class FragmentQuoteSaved extends LifecycleFragment{

    private QuoteViewModel quoteViewModel; //data model
    private SwipeRefreshLayout swipeRefreshLayout;  //swipe to refresh data
    private RecyclerView recyclerView;
    private AdapterQuotesSaved adapterQuotes;
    private List<SavedQuote> quotes;

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_quote_saved,container,false);
        recyclerView = (RecyclerView) view.findViewById(R.id.recycler_view_quotes_saved);
        swipeRefreshLayout = (SwipeRefreshLayout) view.findViewById(R.id.swipe_to_refresh);
        swipeRefreshLayout.setOnRefreshListener(new SwipeRefreshLayout.OnRefreshListener() {
            @Override
            public void onRefresh() {
                //changes will be reflected automatically, thanks to LiveData
                quoteViewModel.refreshData();
            }
        });

        //set up recycler view
        adapterQuotes = new AdapterQuotesSaved(getContext());

        recyclerView.setAdapter(adapterQuotes);
        recyclerView.setLayoutManager(new FragmentQuoteSaved.WrapContentLinearLayoutManager(getContext()));

        return view;
    }

    @Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);

        //create dataModel object
        //remember, doesn't matter how many times this method called, same object will be returned
        quoteViewModel = ViewModelProviders.of(getActivity()).get(QuoteViewModel.class);
        quoteViewModel.init( getArguments().getString("category")
                ,getArguments().getInt("count"));

        adapterQuotes.setModel(quoteViewModel);

        new GetSavedQuotesThread().execute();
    }


    //for catching exception generated by recycler view which was causing abend, no other way to handle this
    class WrapContentLinearLayoutManager extends LinearLayoutManager {
        WrapContentLinearLayoutManager(Context context) {
            super(context);
        }

        //... constructor
        @Override
        public void onLayoutChildren(RecyclerView.Recycler recycler, RecyclerView.State state) {
            try {
                super.onLayoutChildren(recycler, state);
            } catch (IndexOutOfBoundsException ignored) {
            }
        }
    }

    private class GetSavedQuotesThread extends AsyncTask<String, String, List<SavedQuote>> {
        protected List<SavedQuote> doInBackground(String... urls) {
            // Calculate and return retulst
            return quoteViewModel.getQuoteSaved();
        }


        protected void onPostExecute(List<SavedQuote> result) {
            // This is executed in main Thread, use the result
            adapterQuotes.insertItems(result);
        }
    }
}
